# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170419_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='input_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(),
        ),
    ]
